### ISSUE TITLE
Resolver o problema do mapa não carregar em browser (Plugin Diagnostic)

### ISSUE THREAD

**Issue by dgraca** [iptomar/RaulLinoC#70]

**Comment by JKZ02** [comment]
Issue couldn't be solved due to plugin compatibility issues.
To solve this we would have to remove a plugin that is being used to control permissions grant on both android and ios but unfortunately doesn't work on a browser.
Overall not that big of an issue since it only stops the map frame from loading in the browser, nothing else is affected.
